/*
 * FFmpeg embedded version configuration
 * Copyright (c) 2024 Opera Software ASA
 */

#ifndef FFMPEG_EMBEDDED_VERSION_H
#define FFMPEG_EMBEDDED_VERSION_H

/* Version information */
#define LIBAVUTIL_VERSION_MAJOR  58
#define LIBAVUTIL_VERSION_MINOR  29
#define LIBAVUTIL_VERSION_MICRO  100

#define LIBAVCODEC_VERSION_MAJOR  60
#define LIBAVCODEC_VERSION_MINOR  31
#define LIBAVCODEC_VERSION_MICRO  102

#define LIBAVFORMAT_VERSION_MAJOR  60
#define LIBAVFORMAT_VERSION_MINOR  16
#define LIBAVFORMAT_VERSION_MICRO  100

#define LIBSWSCALE_VERSION_MAJOR  7
#define LIBSWSCALE_VERSION_MINOR  5
#define LIBSWSCALE_VERSION_MICRO  100

#define LIBSWRESAMPLE_VERSION_MAJOR  4
#define LIBSWRESAMPLE_VERSION_MINOR  12
#define LIBSWRESAMPLE_VERSION_MICRO  100

/* Configuration */
#define FFMPEG_CONFIGURATION "embedded version for Opera"
#define FFMPEG_LICENSE "LGPL version 2.1"

/* Feature flags */
#define CONFIG_H264_DECODER     1
#define CONFIG_VP8_DECODER      1
#define CONFIG_VP9_DECODER      1
#define CONFIG_AV1_DECODER      1
#define CONFIG_AAC_DECODER      1
#define CONFIG_MP3_DECODER      1
#define CONFIG_VORBIS_DECODER   1
#define CONFIG_OPUS_DECODER     1

#define CONFIG_MP4_DEMUXER      1
#define CONFIG_WEBM_DEMUXER     1
#define CONFIG_OGG_DEMUXER      1
#define CONFIG_HLS_DEMUXER      1
#define CONFIG_DASH_DEMUXER     1

#endif /* FFMPEG_EMBEDDED_VERSION_H */